<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>PayFlow.Web</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\PayFlow.Application\PayFlow.Application.csproj" />
    <ProjectReference Include="..\PayFlow.Infrastructure\PayFlow.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.OpenApi" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="PayFlow.Api.Tests" />
  </ItemGroup>
</Project>
